# Unsupervised learning methods

So far we have seen "Supervised Methods" where interest is in analyzing a _response_ (or outcome) based
on various _predictors_. In many cases, especially for Exploratory Data Analysis, we want methods to extract patterns on
variables without analyzing a specific _response_. Methods for the latter case are called "Unsupervised Methods". Examples are _Principal Component Analysis_ and _Clustering_.

Interpretation of these methods is much more _subjective_ than in Supervised Learning. For example: 
if we want to know if a given _predictor_ is related to _response_, we can perform statistical inference using hypothesis testing. In another example, if we want to know which predictors are useful for prediction: use cross-validation to do model selection. Finally, if we want to see how well we can predict a specific response, we can use cross-validation to report on test error. In unsupervised methods, there is similar clean evaluation methodology. Nonetheless, they can be very useful methods to understand data at hand.

In this chapter we will look at two examples of these methods: clustering with the k-means algorithm, and clustering as part of text analysis using topic modeling.

## K-means

The k-means algorithm partitions observations in a dataset into groups. The goal is that observations within each group are _similar_ 

